
project_type: py
source_dir: /Users/mac/Desktop/gpt_test
target_file: /Users/mac/Desktop/gpt_test/output.txt

model: deepseek_chat
model_max_input_length: 30000
enable_multi_round_generate: false

execute: true
auto_merge: true
human_as_model: true